<?php

    return [
            [
                "titolo"=> "Appartamento Vista Mare",
                "slug"=> "appartamento-vista-mare",
                "user_id"=> null,
                "descrizione"=> "Splendido appartamento con vista sul mare e terrazza panoramica.",
                "category_id"=> 6,
                "prezzo_per_notte"=> 120.00,
                "numero_stanze"=> 3,
                "posti_letto"=> 5,
                "città"=> "Napoli",
                "regione"=> "Campania",
                "indirizzo"=> "Via Posillipo 45",
                "latitudine"=> 40.830031,
                "longitudine"=> 14.223772,
                "wifi"=> true,
                "disponibile"=> true
            ],
            [
                "titolo"=> "Loft Moderno in Centro",
                "slug"=> "loft-moderno-in-centro",
                "user_id"=> null,
                "descrizione"=> "Loft elegante nel cuore della città, vicino a tutti i servizi.",
                "category_id"=> 2,
                "prezzo_per_notte"=> 95.50,
                "numero_stanze"=> 2,
                "posti_letto"=> 3,
                "città"=> "Milano",
                "regione"=> "Lombardia",
                "indirizzo"=> "Via Torino 12",
                "latitudine"=> 45.46420000,
                "longitudine"=> 9.19000000,
                "wifi"=> true,
                "disponibile"=> true
            ],
            [
                "titolo"=> "Rustico in Collina",
                "slug"=> "rustico-in-collina",
                "user_id"=> null,
                "descrizione"=> "Casa rustica immersa nel verde, ideale per relax.",
                "category_id"=> 5,
                "prezzo_per_notte"=> 80.00,
                "numero_stanze"=> 4,
                "posti_letto"=> 6,
                "città"=> "Arezzo",
                "regione"=> "Toscana",
                "indirizzo"=> "Strada della Vigna 8",
                "latitudine"=> 43.46300000,
                "longitudine"=> 11.88000000,
                "wifi"=> false,
                "disponibile"=> true
            ],
            [
                "titolo"=> "Bilocale Accogliente",
                "slug"=> "bilocale-accogliente",
                "user_id"=> null,
                "descrizione"=> "Bilocale luminoso e ben arredato, perfetto per coppie.",
                "category_id"=> 2,
                "prezzo_per_notte"=> 70.00,
                "numero_stanze"=> 2,
                "posti_letto"=> 2,
                "città"=> "Torino",
                "regione"=> "Piemonte",
                "indirizzo"=> "Corso Francia 101",
                "latitudine"=> 45.07050000,
                "longitudine"=> 7.68680000,
                "wifi"=> true,
                "disponibile"=> true
            ],
            [
                "titolo"=> "Villa con Piscina",
                "slug"=> "villa-con-piscina",
                "user_id"=> null,
                "descrizione"=> "Villa spaziosa con piscina privata e giardino.",
                "category_id"=> 3,
                "prezzo_per_notte"=> 250.00,
                "numero_stanze"=> 6,
                "posti_letto"=> 10,
                "città"=> "Firenze",
                "regione"=> "Toscana",
                "indirizzo"=> "Via delle Rose 33",
                "latitudine"=> 43.76960000,
                "longitudine"=> 11.25580000,
                "wifi"=> true,
                "disponibile"=> true
            ],
            [
                "titolo"=> "Monolocale Economico",
                "slug"=> "monolocale-economico",
                "user_id"=> null,
                "descrizione"=> "Piccolo monolocale per soggiorni brevi.",
                "category_id"=> 5,
                "prezzo_per_notte"=> 45.00,
                "numero_stanze"=> 1,
                "posti_letto"=> 1,
                "città"=> "Bologna",
                "regione"=> "Emilia-Romagna",
                "indirizzo"=> "Via Indipendenza 20",
                "latitudine"=> 44.49490000,
                "longitudine"=> 11.34260000,
                "wifi"=> false,
                "disponibile"=> true
            ],
            [
                "titolo"=> "Attico Panoramico",
                "slug"=> "attico-panoramico",
                "user_id"=> null,
                "descrizione"=> "Attico con vista mozzafiato sulla città.",
                "category_id"=> 1,
                "prezzo_per_notte"=> 180.00,
                "numero_stanze"=> 5,
                "posti_letto"=> 7,
                "città"=> "Roma",
                "regione"=> "Lazio",
                "indirizzo"=> "Via del Corso 100",
                "latitudine"=> 41.90280000,
                "longitudine"=> 12.49640000,
                "wifi"=> true,
                "disponibile"=> true
            ],
            [
                "titolo"=> "Casa Vacanze sul Lago",
                "slug"=> "casa-vacanze-sul-lago",
                "user_id"=> null,
                "descrizione"=> "Casa tranquilla con accesso diretto al lago.",
                "category_id"=> 4,
                "prezzo_per_notte"=> 110.00,
                "numero_stanze"=> 3,
                "posti_letto"=> 4,
                "città"=> "Como",
                "regione"=> "Lombardia",
                "indirizzo"=> "Via Lago 5",
                "latitudine"=> 45.80800000,
                "longitudine"=> 9.08520000,
                "wifi"=> true,
                "disponibile"=> true
            ],
            [
                "titolo"=> "Appartamento Artistico",
                "slug"=> "appartamento-artistico",
                "user_id"=> null,
                "descrizione"=> "Decorazioni uniche e atmosfera creativa.",
                "category_id"=> 2,
                "prezzo_per_notte"=> 90.00,
                "numero_stanze"=> 2,
                "posti_letto"=> 3,
                "città"=> "Genova",
                "regione"=> "Liguria",
                "indirizzo"=> "Via Garibaldi 7",
                "latitudine"=> 44.40560000,
                "longitudine"=> 8.94630000,
                "wifi"=> true,
                "disponibile"=> true
            ],
            [
                "titolo"=> "Casa in Montagna",
                "slug"=> "casa-in-montagna",
                "user_id"=> null,
                "descrizione"=> "Perfetta per escursioni e relax invernale.",
                "category_id"=> 4,
                "prezzo_per_notte"=> 85.00,
                "numero_stanze"=> 4,
                "posti_letto"=> 6,
                "città"=> "Trento",
                "regione"=> "Trentino-Alto Adige",
                "indirizzo"=> "Via delle Dolomiti 9",
                "latitudine"=> 46.07000000,
                "longitudine"=> 11.12000000,
                "wifi"=> false,
                "disponibile"=> true
            ]
        ]

?>